name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
        name: Repository Checkout
      - name: Docker Auth
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker Build
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: 
            rodsan/devops4devs-news:latest
            rodsan/devops4devs-news:${{github.run_number}}
  CD:
   needs: [CI]
   runs-on: ubuntu-latest
   steps:
     - name: AWS Settings
       uses: aws-actions/configure-aws-credentials@v4
       with:
         asw-region: "us-east-1"
         aws-access-key-id: ${{secre.AWS_ACCESS_KEY}}
         aws-secret-access-key: ${{secre.AWS_ACCESS_SECRET}}
        
     - name: Deploy
       run: echo "kubectl apply"
     
  
